image: atlassian/default-image:4

pipelines:
  branches:
    develop:
      - step:
          name: Build Static Files
          deployment: staging
          script:
            - pipe: atlassian/ssh-run:0.8.1
              variables:
                SSH_USER: $DEPLOY_USER
                SERVER: $DEPLOY_HOST
                COMMAND: >-
                  cd $DEPLOY_PATH && git remote prune origin && git fetch origin develop && git reset --hard origin/develop && docker run --rm -v $DEPLOY_PATH:/app -w /app -e HOME=/tmp node:22.21-slim bash -c "corepack enable && corepack prepare yarn@1.22.22 --activate && yarn install --frozen-lockfile && yarn generate"


    staging:
      - step:
          name: Build Static Files
          deployment: staging
          script:
            - pipe: atlassian/ssh-run:0.8.1
              variables:
                SSH_USER: $DEPLOY_USER
                SERVER: $DEPLOY_HOST
                COMMAND: >-
                  cd $DEPLOY_STG_PATH && git remote prune origin && git fetch origin staging && git reset --hard origin/staging && docker run --rm -v $DEPLOY_STG_PATH:/app -w /app -e HOME=/tmp node:22.21-slim bash -c "corepack enable && corepack prepare yarn@1.22.22 --activate && yarn install --frozen-lockfile && yarn generate"

